# Generated by Django 3.2.5 on 2021-07-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='category',
            name='technologies',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
